# -*- coding: utf-8 -*-
"""Plant growth analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11UL36S8UpoNVomnCntR6kvIVHhn8btFp
"""

def growth_level(cm):
  if cm>=50:
    return "Excellent growth"
  elif cm>=30:
    return "Healthy growth"
  elif cm>=15:
    return "Moderate growth"
  elif cm>=1:
    return "Slow growth"
  else:
    return "Did not grow"
def calculate_avg(plants):
  total = 0
  for plant in plants:
    total += plant["cm"]
  return total/len(plants)
def tallest_plant(plants):
  top = plants[0]
  for plant in plants:
    if plant["cm"]>top["cm"]:
      top = plant
  return top
def shortest_plant(plants):
  low = plants[0]
  for plant in plants:
    if plant["cm"]<low["cm"]:
      low = plant
  return low
plants = []
num_plants = int(input("Enter number of plants: "))
for i in range(num_plants):
  print(f"\nPlant {i+1}")
  plant_type = input("Enter plant's type: ")
  cm = int(input("Height (in cm): "))
  plants.append({
      "type" : plant_type,
      "cm" : cm
  })
print("\nPlant Report\n")

if not plants:
  print("No plant data to report.")
else:
  for plant in plants:
    level = growth_level(plant["cm"])
    print(
        f"Plant Type: {plant['type']} | "
        f"Height: {plant['cm']} cm | "
        f"Growth Level: {level}"
        )
  print("\nSummary")
  avg = calculate_avg(plants)
  top = tallest_plant(plants)
  low = shortest_plant(plants)
  print(f"Average Height:{avg:.2f} cm")
  print(f"Highest Plant:{top['typer']} ({top['cm']} cm)")
  print(f"Shortest Plant:{low['type']} ({low['cm']} cm)")